### PR TITLE
new exercise added

### PR DESCRIPTION
**Pull request by prabakaranravi23**
2 files created and added

### CODE REVIEW

**Comment by jeevaengg21** [comment]
1. Remove the Signature image from resume and repository. Do not disclose personal information.
2. Remove the declaration content from Footer and keep it empty for next exercise

**Comment by prabakaranravi23** [comment]
corrections done

**Comment by prabakaranravi23** [comment]
corrections done

**Comment by prabakaranravi23** [comment]
now it is corrected anna

**Review by jeevaengg21 — APPROVED** [review]

**Pull request merged**
